geodjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers

from world import api_views

router = routers.DefaultRouter()
router.register(r'area', api_views.AreaViewSet, base_name='area')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'^world/', include('world.urls', namespace='world')),
    url(r'^world-ac/', include('world.dal_urls', namespace='world-ac')),
]

world/urls.py
from django.conf.urls import url
from . import views
from . import dal_views

urlpatterns = [
    url(r'^area/$', views.AreaFilterView.as_view(),
        name='area_list'),
    url(
        r'^area/(?P<pk>[0-9]+)$', views.AreaDetailView.as_view(),
        name='area_detail'),
    url(
        r'^area/create/$', views.AreaCreate.as_view(),
        name='area_create'),
    url(
        r'^area/update/(?P<pk>[0-9]+)$', views.AreaUpdate.as_view(),
        name='area_update'),
    url(r'^source/$', views.SourceFilterView.as_view(),
        name='source_list'),
    url(
        r'^source/(?P<pk>[0-9]+)$', views.SourceDetailView.as_view(),
        name='source_detail'),
    url(
        r'^source/create/$', views.SourceCreate.as_view(),
        name='source_create'),
    url(
        r'^source/update/(?P<pk>[0-9]+)$', views.SourceUpdate.as_view(),
        name='source_update'),
]

world/models.py
from django.contrib.gis.db import models
from django.core.urlresolvers import reverse
from django.contrib.postgres.fields import HStoreField
from datetime import datetime
from .validators import date_validator
import re
# automatically genereated by
# $ python manage.py ogrinspect world/data/TM_WORLD_BORDERS/TM_WORLD_BORDERS-0.3.shp WorldBorder


class Source(models.Model):
    name = models.CharField(max_length=255)
    original_url = models.URLField(blank=True, null=True)
    downloaded = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('world:source_detail', kwargs={'pk': self.id})


class Area(models.Model):
    TYPE_CHOICES = (
        ('Country', 'Country'),
        ('ADM1', 'ADM1'),
        ('ADM2', 'ADM2'),
        ('PPLC', 'PPLC'),
        ('PPL', 'PPL'),
        ('', '---------'),
    )
    political = models.NullBooleanField()
    geographical = models.NullBooleanField()
    historical = models.NullBooleanField()
    name = models.CharField(max_length=255)
    area_type = models.CharField(max_length=255, blank=True, null=True, choices=TYPE_CHOICES)
    source = models.ForeignKey('Source', blank=True, null=True)
    geonames_id = models.IntegerField(blank=True, null=True)
    legacy_properties = HStoreField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    start_date_written = models.CharField(
        max_length=255, blank=True, null=True,
        validators=[date_validator, ], verbose_name="Start",
        help_text="Please enter a date (DD).(MM).YYYY")
    end_date_written = models.CharField(
        max_length=255, blank=True, null=True,
        validators=[date_validator, ], verbose_name="End",
        help_text="Please enter a date (DD).(MM).YYYY")
    geom = models.MultiPolygonField()
    objects = models.GeoManager()

    def save(self, *args, **kwargs):
        """Adaption of the save() method of the class to automatically parse string-dates into date objects
        """
        def match_date(date):
            """Function to parse string-dates into python date objects.
            """
            date = date.strip()
            date = date.replace('-', '.')
            if re.match(r'[0-9]{4}$', date):
                dr = datetime.strptime(date, '%Y')
                dr2 = date
            elif re.match(r'[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{4}$', date):
                dr = datetime.strptime(date, '%d.%m.%Y')
                dr2 = date
            elif re.match(r'[0-9]{4}\.\.\.$', date):
                dr = datetime.strptime(date, '%Y...')
                dr2 = re.match(r'([0-9]{4})\.\.\.$', date).group(1)
            elif re.match(r'[0-9]{4}\.[0-9]{1,2}\.\.$', date):
                dr = datetime.strptime(date, '%Y.%m..')
                dr2 = re.match(r'([0-9]{4})\.([0-9]{1,2})\.\.$', date).group(2)
                +'.' + \
                    re.match(r'([0-9]{4})\.([0-9]{1,2})\.\.$', date).group(1)
            elif re.match(r'[0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2}$', date):
                dr = datetime.strptime(date, '%Y.%m.%d')
                dr3 = re.match(
                    r'([0-9]{4})\.([0-9]{1,2})\.([0-9]{1,2})$', date)
                dr2 = dr3.group(3) + '.' + dr3.group(2) + '.' + dr3.group(1)
            else:
                dr = None
                dr2 = dr2 = date
            return dr, dr2
        if self.start_date_written:
            self.start_date, self.start_date_written = match_date(
                self.start_date_written)
        if self.end_date_written:
            self.end_date, self.end_date_written = match_date(
                self.end_date_written)
        super(Area, self).save(*args, **kwargs)
        return self

    @property
    def centroid(self):
        centroid = self.geom.centroid
        coordinates = [centroid.y, centroid.x]
        return coordinates

    @property
    def longitude(self):
        centroid = self.geom.centroid
        return centroid.y

    @property
    def latitude(self):
        centroid = self.geom.centroid
        return centroid.x

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('world:area_detail', kwargs={'pk': self.id})


class Label(models.Model):
    CHOICES_LABELTYPE = (
        ('alternateName', 'alternateName'),
        ('officialName', 'officialName'),
    )

    name = models.CharField(max_length=255, blank=True)
    label_type = models.CharField(
        max_length=255, choices=CHOICES_LABELTYPE, blank=True)
    iso_code = models.CharField(max_length=3, blank=True)
    area = models.ForeignKey(Area, blank=True, null=True)

    def __str__(self):
        return self.name


class AreaArea(models.Model):

    RELATIONTYPE_CHOICES = (
        ('parentCountry', 'parentCountry'),
        ('parentADM1', 'parentADM1'),
        ('parentADM2', 'parentADM2'),
        ('parentADM3', 'parentADM3'),
        ('predecessor', 'predecessor'),
        ('unspecified historical relation', 'unspecified historical relation'),
        ('unspecified geographical relation', 'unspecified geographical relation'),
    )
    RELATIONTYPE_CHOICES_REVERSE = {
        'parentCountry': 'ChildOfCountry',
        'parentADM1': 'childADM1',
        'parentADM2': 'childADM2',
        'parentADM3': 'childADM3',
        'predecessor': 'successor',
        'unspecified historical relation': 'unspecified historical relation',
        'unspecified geographical relation': 'unspecified geographical relation'
    }

    related_areaA = models.ForeignKey(Area, blank=True, null=True, related_name='related_areaA')
    related_areaB = models.ForeignKey(Area, blank=True, null=True, related_name='related_areaB')
    relation_type = models.CharField(max_length=50, choices=RELATIONTYPE_CHOICES, blank=True)

world/forms.py
from django import forms
from leaflet.forms.widgets import LeafletWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Area, Source


class GenericFilterFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(GenericFilterFormHelper, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_class = 'genericFilterForm'
        self.form_method = 'GET'
        self.add_input(Submit('Filter', 'Filter'))


class AreaForm(forms.ModelForm):
    class Meta:
        model = Area
        fields = "__all__"
        widgets = {'geom': LeafletWidget(attrs={
            'settings_overrides': {
                'DEFAULT_CENTER': (6.0, 45.0),
            }
        })}

    def __init__(self, *args, **kwargs):
        super(AreaForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-1'
        self.helper.field_class = 'col-md-11'
        self.helper.add_input(Submit('submit', 'save'),)


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = "__all__"
        widgets = {'geom': LeafletWidget(attrs={
            'settings_overrides': {
                'DEFAULT_CENTER': (6.0, 45.0),
            }
        })}

    def __init__(self, *args, **kwargs):
        super(SourceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-1'
        self.helper.field_class = 'col-md-11'
        self.helper.add_input(Submit('submit', 'save'),)

world/views.py
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django_tables2 import SingleTableView, RequestConfig
from .models import Area, Source
from .forms import AreaForm, SourceForm, GenericFilterFormHelper
from .filters import SourceListFilter, AreaListFilter
from .tables import AreaTable, SourceTable


class GenericListView(SingleTableView):
    filter_class = None
    formhelper_class = None
    context_filter_name = 'filter'
    paginate_by = 25

    def get_queryset(self, **kwargs):
        qs = super(GenericListView, self).get_queryset()
        self.filter = self.filter_class(self.request.GET, queryset=qs)
        self.filter.form.helper = self.formhelper_class()
        return self.filter.qs

    def get_table(self, **kwargs):
        table = super(GenericListView, self).get_table()
        RequestConfig(self.request, paginate={
            'page': 1, 'per_page': self.paginate_by}).configure(table)
        return table

    def get_context_data(self, **kwargs):
        context = super(GenericListView, self).get_context_data()
        context[self.context_filter_name] = self.filter
        return context


class AreaFilterView(GenericListView):
    model = Area
    table_class = AreaTable
    template_name = 'world/area_filter.html'
    filter_class = AreaListFilter
    formhelper_class = GenericFilterFormHelper


class SourceFilterView(GenericListView):
    model = Source
    table_class = SourceTable
    template_name = 'world/source_filter.html'
    filter_class = SourceListFilter
    formhelper_class = GenericFilterFormHelper


class AreaDetailView(DetailView):

    model = Area
    template_name = 'world/area_detail.html'

    def get_context_data(self, **kwargs):
        context = super(AreaDetailView, self).get_context_data(**kwargs)
        try:
            context["next_entry"] = Area.objects.filter(id__gt=int(self.kwargs['pk']))[0].pk
        except:
            context["next_entry"] = None
        try:
            prev = [x.id for x in Area.objects.filter(id__lt=int(self.kwargs['pk']))][-1]
        except:
            prev = Area.objects.get(id=self.kwargs['pk'])
        try:
            Area.objects.get(id=int(prev)-1)
            context["previous_entry"] = prev
        except:
            context["previous_entry"] = None
        print(context['previous_entry'])
        return context


class AreaListView(ListView):

    model = Area
    template_name = 'world/area_list.html'


class AreaCreate(CreateView):

    model = Area
    template_name = 'world/area_create.html'
    form_class = AreaForm


class AreaUpdate(UpdateView):

    model = Area
    form_class = AreaForm
    template_name = 'world/area_create.html'


class SourceDetailView(DetailView):

    model = Source
    template_name = 'world/source_detail.html'


class SourceListView(ListView):

    model = Source
    template_name = 'world/source_list.html'


class SourceCreate(CreateView):

    model = Source
    template_name = 'world/source_create.html'
    form_class = SourceForm


class SourceUpdate(UpdateView):

    model = Source
    form_class = SourceForm
    template_name = 'world/source_create.html'

world/templates/world/area_create.html
{% extends "webpage/base.html" %}
{% load leaflet_tags %}
{% block Titel %} Create/Modify Area {% endblock %} 
{% block content %}
{% leaflet_js plugins="forms" %}
{% leaflet_css plugins="forms" %}

{% load crispy_forms_tags %}

<style>

    .leaflet-container {  /* all maps */
        height: 800px;
    }

</style>

<div class="container">
<div class="panel panel-default">
    <div class="panel-heading">
        <h1>Create/Edit Area</h1>
    </div>
    <div class="panel-body">
         {% crispy form %}
    </div>
</div>
</div>
{% endblock content %}

world/templates/world/area_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block scriptHeader %}
<link rel="stylesheet" href="{% static 'world/leaflet/leaflet.css' %}"/></link>
<link rel="stylesheet" href="{% static 'world/leaflet.markercluster/dist/MarkerCluster.css' %}"/></link>
<link rel="stylesheet" href="{% static 'world/leaflet.markercluster/dist/MarkerCluster.Default.css' %}"/></link>
<script src="{% static 'world/leaflet/leaflet.js' %}"></script>
<script src="{% static 'world/leaflet.markercluster/src/leaflet.markercluster-src.js' %}"></script>
<script src="{% static 'world/leaflet.ajax/leaflet.ajax.js' %}"></script>
<style>
    #map { height: 800px; }
</style>
{% endblock %}
{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-2">
                {% if previous_entry %}
                    <h2>
                        <a href="{% url 'world:area_detail' pk=previous_entry %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true" title="previous area"></span></a>
                    </h2>
                {% endif %}
                </div>
                <div class="col-md-8">
                    <h2 style="text-align:center;">{{ object.name }}</h2>
                    <h4 style="text-align:center;">
                        <span data-toggle="modal" data-target="#myModal" title="click to toggle info" class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    </h4>
                </div>
                <div class="col-md-2">
                {% if next_entry %}
                    <h2>
                        <a href="{% url 'world:area_detail' pk=next_entry %}" style="float:right"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true" title="next area"></span></a>
                    </h2>
                {% endif %}
                </div>
            </div>
        </div>
        <div class="panel panel-body">
            <div id="map"/>
        </div>
    </div>

    <!-- Modal -->
      <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
        
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title" style="text-align:center;">{{ object.name }}</h4>
            </div>
            <div class="modal-body">
              <table class="table table-bordered table-striped table-hover">
                <tr>
                    <th>source</th>
                    <td><a href="{% url 'world:source_detail' pk=object.source.id %}"> {{ object.source }} <a href="{{ object.source.original_url }}"><span data-toggle="modal" data-target="#myModal" title="download original data set" class="glyphicon glyphicon-download-alt" aria-hidden="true"></span></a></td>
                </tr>
                <tr>
                    <th>legacy_properties</th>
                    <td>{% for key, value in object.legacy_properties.items %} {{ key }}: {{ value}} <br/>{% endfor %}</td>
                </tr>
                <tr>
                    <th>start_date</th>
                    <td>{{ object.start_date }}</td>
                </tr>
                <tr>
                    <th>end_date</th>
                    <td>{{ object.end_date }}</td>
                </tr>
                <tr>
                    <th>To geojson</th>
                    <td><a href="{% url 'area-detail' pk=object.pk %}?format=json">{{ object.centroid }}</a></td>
                </tr>
            </table>
            {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'world:area_update' pk=object.pk %}" role="button">edit Area</a>
            {% endif %}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
          
        </div>
      </div>
    <!-- Modal end -->


    <script type="text/javascript">
        
        var mymap = L.map('map', {
          fullscreenControl: true,
          }).setView([{{ object.longitude }} ,{{ object.latitude }}], 10);

        var baseLayer = L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ',
        });

        baseLayer.addTo(mymap);

        L.geoJson.ajax("{% url 'area-detail' pk=object.pk %}?format=json").addTo(mymap);

        var defaultLayers = {
            "Default": baseLayer
        }
        
        var overlayMaps = {
            "Dinamlex": L.tileLayer('https://maps.acdh.oeaw.ac.at/mapserv?map=/data/test.map&mode=tile&layers=test&tilemode=gmap&tile={x}+{y}+{z}', {'maxZoom': 18, 'opacity': 0.7}),
            "Tirol": L.tileLayer('https://maps.acdh.oeaw.ac.at/mapserv?map=/data/tirol.map&mode=tile&layers=tirol&tilemode=gmap&tile={x}+{y}+{z}', {'maxZoom': 18, 'opacity': 0.7}),
            "Czoernig": L.tileLayer('https://maps.acdh.oeaw.ac.at/mapserv?map=/data/czoernig.map&mode=tile&layers=czoernig&tilemode=gmap&tile={x}+{y}+{z}', {'maxZoom': 18, 'opacity': 0.7})
        };
        L.control.layers(defaultLayers, overlayMaps).addTo(mymap);
    </script>
{% endblock %}

world/templates/world/area_filter.html
{% extends "world/generic_list.html" %}
{% block Titel %}Browse Area{% endblock %}
{% block list_title %}Browse Area
    {% if user.is_authenticated %}
        | <a class ="btn btn-success"  href="{% url 'world:area_create' %}">Create new Area</a>
    {% endif %}
{% endblock %}

{% block reset_button %}
<!-- <a class ="btn btn-default"  id="01">Show/Hide Advanced search options</a></br> -->
 <p></p>
 <a class ="btn btn-default"  href="{% url 'world:area_list' %}">Reset search</a>     
{% endblock %}

{% block customScripts %}
{% endblock %}

world/templates/world/generic_list.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Titel %} {% endblock %}
{% block scriptHeader %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'webpage/libraries/jquery.autocomplete/jquery.autocomplete.css' %}"/>
<script src="{% static 'webpage/libraries/jquery.autocomplete/jquery.autocomplete.js' %}"></script> -->
{% endblock %}
{% block content %}
<div class="container">
<div class="panel panel-default">
    <div class="panel-heading">
    
        <h1>{% block list_title %}{% endblock %}</h1>
    
    {% block create_button %}
        
    {% endblock %}
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                {% load django_tables2 crispy_forms_tags %}
                {% crispy filter.form filter.form.helper %}
                {% block reset_button %}
                {% endblock %}
            </div>
            <div class="col-md-8">
                {% render_table table %}
            </div>
        </div>
    </div>
</div>
</div>
{% block customScripts %}{% endblock %}
{% endblock %}

world/templates/world/source_create.html
{% extends "webpage/base.html" %}
{% load leaflet_tags %}
{% block Titel %} Create/Modify Source {% endblock %} 
{% block content %}

{% load crispy_forms_tags %}


<div class="container">
<div class="panel panel-default">
    <div class="panel-heading">
        <h1>Create/Edit Source</h1>
    </div>
    <div class="panel-body">
         {% crispy form %}
    </div>
</div>
</div>
{% endblock content %}

world/templates/world/source_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}

{% block content %}


<h1>{{ object }}</h1>
<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>Name</th>
        <td>{{ object.name }}</td>
    </tr>
    <tr>
        <th>original_url</th>
        <td><a href="{{ object.original_url }}">{{ object.original_url}}</a></td>
    </tr>
    <tr>
        <th>downloaded</th>
        <td>{{ object.downloaded }}</td>
    </tr>
</table>
{% if user.is_authenticated %}
<a class="btn btn-primary" href="{% url 'world:source_update' pk=object.pk %}" role="button">edit Source</a>
{% endif %}
{% endblock %}

world/templates/world/source_filter.html
{% extends "world/generic_list.html" %}
{% block Titel %}Browse Source{% endblock %}
{% block list_title %}Browse Source
    {% if user.is_authenticated %}
        | <a class ="btn btn-success"  href="{% url 'world:source_create' %}">Create new Source</a>
    {% endif %}
{% endblock %}

{% block reset_button %}
<!-- <a class ="btn btn-default"  id="01">Show/Hide Advanced search options</a></br> -->
 <p></p>
 <a class ="btn btn-default"  href="{% url 'world:source_list' %}">Reset search</a>     
{% endblock %}

{% block customScripts %}
{% endblock %}