django_spaghetti/urls.py
from django.conf.urls import url
from django_spaghetti.views import plate

urlpatterns = [
    url(r'^$', plate, name='plate'),
]

geodjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers

from world import api_views

router = routers.DefaultRouter()
router.register(r'area', api_views.AreaViewSet, base_name='area')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
    url(r'^world/', include('world.urls', namespace='world')),
    url(r'^world-ac/', include('world.dal_urls', namespace='world-ac')),
]

webpage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.start_view, name="start"),
    url(r'^imprint/$', views.imprint_view, name='imprint'),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
]

world/urls.py
from django.conf.urls import url
from . import views
from . import dal_views

urlpatterns = [
    url(r'^area/$', views.AreaFilterView.as_view(),
        name='area_list'),
    url(
        r'^area/(?P<pk>[0-9]+)$', views.AreaDetailView.as_view(),
        name='area_detail'),
    url(
        r'^area/create/$', views.AreaCreate.as_view(),
        name='area_create'),
    url(
        r'^area/update/(?P<pk>[0-9]+)$', views.AreaUpdate.as_view(),
        name='area_update'),
    url(r'^source/$', views.SourceFilterView.as_view(),
        name='source_list'),
    url(
        r'^source/(?P<pk>[0-9]+)$', views.SourceDetailView.as_view(),
        name='source_detail'),
    url(
        r'^source/create/$', views.SourceCreate.as_view(),
        name='source_create'),
    url(
        r'^source/update/(?P<pk>[0-9]+)$', views.SourceUpdate.as_view(),
        name='source_update'),
]

webpage/models.py
from django.db import models

# Create your models here.

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class form_user_login(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(form_user_login, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Login'))

webpage/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from .forms import form_user_login
from .metadata import PROJECT_METADATA as PM


def start_view(request):
    if PM is not None:
        context = {"metadata": PM}
    else:
        context = {}

    return render(request, 'webpage/index.html', context)


def imprint_view(request):
    if PM is not None:
        context = {"metadata": PM}
    else:
        context = {}

    return render(request, 'webpage/imprint.html', context)


#################################################################
#               views for login/logout                          #
#################################################################

def user_login(request):
    if request.method == 'POST':
        form = form_user_login(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(request.GET.get('next', '/'))
                else:
                    return HttpResponse('not active.')
            else:
                return HttpResponse('user does not exist')
    else:
        form = form_user_login()
        return render(request, 'webpage/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return render_to_response('webpage/user_logout.html')

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block Titel %} About {% endblock %}

{% block content %}
    <div class="container">
        <h1>{% projects_metadata 'title' %}</h1>
    </div>
{% endblock %}

webpage/templates/webpage/base.html
{% load staticfiles %}
{% load webpage_extras %}

<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>{% block Titel %} {% projects_metadata 'title' %}{% endblock %}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {% block metaDescription %}
      <meta name="description" content="{{ metadata.description }}">
      {% endblock %}
      <meta name="author" content="{{ metadata.author }}">
      <!-- Bootstrap -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/bootstrap335/css/bootstrap.min.css' %}"/></link>
      <!-- custom css -->
      <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}"/></link>
      <!--scroll to top CSS -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}"></link>
      <!-- jQuery -->
      <script type="text/javascript" src="{% static 'webpage/libraries/jquery/jquery.js' %}"></script>
      <!--scroll to top -->
      <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>
      <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
        <script type="text/javascript">
            window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":"{% url 'webpage:imprint' %}","theme":"dark-bottom"};
        </script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
        <!-- End Cookie Consent plugin -->
        <!-- cool-share plugin http://tutorialzine.com/2014/08/cool-share-jquery-plugin/ -->
            <link rel="stylesheet" href="{% static 'webpage/libraries/cool-share/plugin.css' %}"/></link>
            <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" />
            <script src="{% static 'webpage/libraries/cool-share/plugin.js' %}"/></script>
        <!-- End fo cool-share -->
        <!-- Piwik -->
          <script type="text/javascript">
            var _paq = _paq || [];
            _paq.push(["setDomains", ["*.geodjango.acdh.oeaw.ac.at/","*.geodjango.eos.arz.oeaw.ac.at"]]);
            _paq.push(['trackPageView']);
            _paq.push(['enableLinkTracking']);
            (function() {
              var u="//piwik.apollo.arz.oeaw.ac.at/";
              _paq.push(['setTrackerUrl', u+'piwik.php']);
              _paq.push(['setSiteId', '50']);
              var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
              g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
            })();
          </script>
          <noscript><p><img src="//piwik.apollo.arz.oeaw.ac.at/piwik.php?idsite=50" style="border:0;" alt="" /></p></noscript>
          <!-- End Piwik Code -->

      {% block scriptHeader %}
      {% endblock %}
  </head>

  <body role="document">
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation!</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
        </div>  
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Home
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'webpage:start' %}">{% projects_metadata 'title' %}</a>
                    </li>
                    <li>
                        <a href="{% url 'datamodel:plate' %}">Application's data model</a>
                    </li>
                    <li>
                        <a href="{% url 'webpage:imprint' %}">Impressum / Imprint</a>
                    </li>
                  </ul>
              </li>
               <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse the Data
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'world:area_list' %}">Areas</a>
                    </li>
                    <li>
                        <a href="{% url 'world:source_list' %}">Sources</a>
                    </li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">API
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'api-root' %}">JSON</a>
                    </li>
                  </ul>
                </li>
                <!-- <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Analyze the Data
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    
                  </ul>
                </li> -->
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                {% if user.is_authenticated %}
                  <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"/>&nbsp;{{ user.get_username }}
                  </a>
                  <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'webpage:user_login' %}">Log-In</a>
                        </li>
                        <li>
                            <a href="{% url 'webpage:user_logout' %}">Log-Out</a>
                        </li>
                      </ul>
                {% else %}
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"/>
                  </a>
                      <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'webpage:user_login' %}">Log-In</a>
                        </li>
                        <li>
                            <a href="{% url 'webpage:user_logout' %}">Log-Out</a>
                        </li>
                      </ul>
                {% endif %}
              </li>
            </ul>
        </div>
    </nav>
    <div class="alert alert-danger">
      <strong>Be Aware!</strong> This Site/Service is at a very early state of developement. Everything can change at any time.
    </div>

    <section class="main-content">
      <div id="content" class="container">
        {% block content %}
        {% endblock %}
      </div>
    </section>
    
    <div align="text-center">
        <span class="socialShare"> <!-- The share buttons will be inserted here --> </span>
      </div>

    <footer>
      <div class="row text-center">
        <div class="col-sm-4">
          <a href="https://acdh.oeaw.ac.at/acdh/" class="navlink" target="_blank">
              <img src="{% static 'webpage/img/ACDH_kurz_Weiss.png' %}" alt="ACDH" width="25%"/>   
          </a>
        </div>
        <div class="col-sm-4">
            <a href="{% projects_metadata 'github' %}" class="navlink" target="_blank">
              <img src="{% static 'webpage/img/GitHub-Mark-Light-64px.png' %}" alt="{{ metadata.github }}" width="10%"/>   
            </a>
        </div>
        <!-- <div class="col-sm-4">
            <a href="https://creativecommons.org/licenses/by-sa/4.0/" class="navlink" target="_blank">
              <img src="{% static 'webpage/img/by-sa.png' %}" alt="CC-BY-SA-4.0" width="25%"/>                 
            </a>
        </div> -->
      </div>  
    </footer>
    {% block scripts %}
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap-tab.js' %}"></script>
    <!-- cool share -->
      <script type="text/javascript">
        $(function (){
          var options = {
            twitter: {
              text: '',
              via: ''
            },
            facebook : true,
            googlePlus : true
          };
          $('.socialShare').shareButtons(options);
        });
      </script>
    <!-- scroll-up-bottom -->        
    <script type="text/javascript">
            // Setup plugin with default settings
            $(document).ready(function() {
                $.apScrollTop({
                    'onInit': function(evt) {
                        console.log('apScrollTop: init');
                    }
                });
            });
    </script>    
    {% endblock %}
  </body>
</html>

webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}

<!-- Launch modal on page load http://stackoverflow.com/questions/10233550/launch-bootstrap-modal-on-page-load -->
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">Confirm delete</h3>
      </div>
      <div class="modal-body">
       	<form action="" method="post">{% csrf_token %}
    		<h4>Are you sure you want to delete the {{ object.get_classname }}:<br /> <strong>{{ object }}</strong> ?</h4>
    		<input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
		</form>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>
</form>
{% endblock content %}
{% block scripts %}
{{block.super}}
<script type="text/javascript">
$(window).load(function(){
        $('#myModal').modal('show');
    });
</script>


{% endblock scripts %}

webpage/templates/webpage/imprint.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block Titel %} Imprint {% endblock %}
{% block content %}
<div class="container">
        <div class="imprint">
            <h1>Impressum | imprint</h1>
            <div lang="ger">
                <h1>Offenlegung gemäß §§ 24, 25 Mediengesetz und § 5 E-Commerce-Gesetz</h1>
                <h2>Medieninhaberin, Herausgeberin, inhaltliche und redaktionelle Verantwortung, Dienstanbieterin:</h2>
                <p>
                    <a href="http://www.oeaw.ac.at">Österreichische Akademie der Wissenschaften</a>
                    <br/>
                    Juristische Person öffentlichen Rechts (BGBl 569/1921 idF BGBl I 130/2003)<br/>
                    <a href="https://acdh.oeaw.ac.at">Austrian Centre for Digital Humanities (ACDH)</a>
                    <br/>
                    Dr. Ignaz Seipel-Platz 2, 1010 Wien, Österreich<br/>
                    E-Mail: <a href="mailto:acdh-tech@oeaw.ac.att" style="color:black">acdh-tech@oeaw.ac.at</a>
                </p>
                <h2>Unternehmensgegenstand:</h2>
                <p>
                    Die Österreichische Akademie der Wissenschaften (ÖAW) hat den gesetzlichen Auftrag, die Wissenschaft in jeder Hinsicht zu fördern. Als Gelehrtengesellschaft pflegt die ÖAW den Diskurs und die Zusammenarbeit der Wissenschaft mit Öffentlichkeit, Politik und Wirtschaft. <br/>
                    Das Austrian Centre for Digital Humanities (ACDH) ist ein Institut der ÖAW, das mit dem Ziel gegründet wurde, digitale Methoden und Ansätze in den geisteswissenschaftlichen Disziplinen zu fördern. Das ACDH unterstützt digitale Forschung in vielfältiger Weise.<br/>
                    {% projects_metadata 'purpose_de' %}
                    
                </p>
                <h2>Vertretungsbefugte Organe:</h2>
                <p>
                    Präsident: Univ.-Prof. Dr. Anton Zeilinger<br/>
                    Vizepräsident: Univ.-Doz. Dr. phil. Michael Alram<br/>
                    Klassenpräsidentin: Univ.-Prof. Dr. Brigitte Mazohl, <br/>
                    Klassenpräsident: Univ.-Prof. Dipl.-Ing. Dr.techn. Georg Brasseur<br/>
                    Als Aufsichtsorgan besteht der Akademierat. Siehe mehr dazu unter <a href="http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/">http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/</a>
                </p>
                <h2>Grundlegende Richtung:</h2>
                <p>
                    {% projects_metadata 'purpose_de' %}
                </p>
                <h2>Haftungsausschluss:</h2>
                <p>
                    Die Österreichische Akademie der Wissenschaften übernimmt keinerlei Gewähr für die Aktualität, Korrektheit, Vollständigkeit oder Qualität der bereitgestellten Informationen.<br/>
                    Im Falle des Bestehens von Links auf Webseiten anderer Medieninhaber, für deren Inhalt die ÖAW weder direkt oder indirekt mitverantwortlich ist, übernimmt die ÖAW keine Haftung für deren Inhalte und schließt jegliche Haftung hierfür aus.
                    
                </p>
                <!-- <h2>Urheberrechtlicher Hinweis:</h2>
                <p>
                    Diese Seite und ihre Inhalte sind, sofern nicht anders gekennzeichnet, unter der creative commons Lizenz <a href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a> International lizensiert (Namensnennung – Weitergabe unter gleichen Bedingungen).
                </p> -->
                <h2>Datenschutzrechtlicher Hinweis:</h2>
                <p>
                    Wir weisen darauf hin, dass zum Zwecke der Systemsicherheit und der Übersicht über das Nutzungsverhalten der Besuchenden im Rahmen von Cookies diverse personenbezogene Daten (Besuchszeitraum, Betriebssystem, Browserversion, innere Auflösung des Browserfensters, Herkunft nach Land, wievielter Besuch seit Beginn der Aufzeichnung) mittels <a href="http://piwik.org/">Piwik-Tracking</a> gespeichert werden. Die Daten werden bis auf weiteres gespeichert. Soweit dies erfolgt, werden diese Daten nicht ohne Ihre ausdrückliche Zustimmung an Dritte weitergegeben.<br/>
                    Durch die Nutzung der Website erklären Sie sich mit der Art und Weise sowie dem Zweck der Datenverarbeitung einverstanden. Durch eine entsprechende Einstellung in Ihrem Browser können Sie die Speicherung der Cookies verhindern. In diesem Fall stehen Ihnen aber gegebenenfalls nicht alle Funktionen der Website zur Verfügung.<br/>
                    Die im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten dürfen von Dritten nicht zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien verwendet werden. Einer derartigen Verwendung wird hiermit ausdrücklich widersprochen.
                    
                </p>
            </div>
            <hr/>
            <div lang="eng">
                <h1>Legal disclosure according to §§ 24, 25 Austrian media law and § 5 E-Commerce law</h1>
                <h2>Media owner, publisher, responsible for content and editorial office, service provider:</h2>
                <p>
                    <a href="http://www.oeaw.ac.at">Austrian Academy of Sciences</a>
                    <br/>
                    Corporate body organized under public law (BGBl 569/1921 idF BGBl I 130/2003)<br/>
                    <a href="https://acdh.oeaw.ac.at">Austrian Centre for Digital Humanities (ACDH)</a>
                    <br/>
                    Dr. Ignaz Seipel-Platz 2, 1010 Vienna, Austria<br/>
                    E-Mail: <a href="mailto:acdh-tech@oeaw.ac.att" style="color:black">acdh-tech@oeaw.ac.at</a>
                </p>
                <h2>Nature and purpose of the business:</h2>
                <p>
                    The Austrian Academy of Sciences (OEAW) has the legal duty to support the sciences and humanities in every respect. As a learned society, the OEAW fosters discourse and cooperation between science and society, politics and economy.<br/>
                    The Austrian Centre for Digital Humanities (ACDH) is an OEAW institute founded with the goal to support digital methods in arts and humanities disciplines. The ACDH supports digital research in manifold ways.<br/>
                    {% projects_metadata 'purpose_en' %}
                </p>
                <h2>Signing power:</h2>
                <p>
                    President: Univ.-Prof. Dr. Anton Zeilinger<br/>
                    Vice president: Univ.-Doz. Dr. phil. Michael Alram<br/>
                    Class presidents: Univ.-Prof. Dr. Brigitte Mazohl, Univ.-Prof. Dipl.-Ing. Dr.techn. Georg Brasseur<br/>
                    Supervisory body:  Academy council. For more information, please visit <a href="http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/">http://www.oeaw.ac.at/die-oeaw/gremien-der-oeaw/akademierat/</a>
                </p>
                <h2>Main aim:</h2>
                <p>
                    {% projects_metadata 'purpose_en' %}
                </p>
                <h2>Disclaimer:</h2>
                <p>
                    The Austrian Academy of Sciences does not take responsibility for the nature, accuracy, entirety or quality of the provided information.<br/>
                    In the case of links to websites of other media owners, whose content the OEAW is neither directly nor indirectly responsible for, the OEAW does not assume liability for their content and excludes any liability in this case.
                </p>
                <!-- <h2>Copyright notice:</h2>
                <p>
                    This website and its content is, unless indicated otherwise, licensed under a creative commons <a href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a> International license (Attribution – Share alike).
                </p> -->
                <h2>Data privacy notice:</h2>
                <p>
                    This is a notice to indicate that for reasons of system security and overview of user behavior, personal data of users of this website (visiting period, operating system, browser version, browser resolution, country of origin, number of visits) will be stored using cookies and <a href="http://piwik.org/">piwik tracking</a>. Data will be stored until further notice. Data will not be disseminated without your explicit consent.<br/>
                    By using this website, you agree to the manner and purposes of data processing. You can disable cookies in your browser settings. However, this might limit functionality of this website.<br/>
                    The contact data published in the context of the imprint duty may not be used to send promotional or informational material not explicitly requested. We explicitly disagree with this usage. 
                </p>
            </div>
        </div>
    </div>
{% endblock %}

webpage/templates/webpage/index.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load webpage_extras %}
{% block content %}

<div class="container text-center">
    <div id="myCarousel" class="carousel slide" data-ride="carousel"><!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"/>
            <li data-target="#myCarousel" data-slide-to="1"/>
        </ol><!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="{% static 'webpage/img/ACDH_Panorama_Postkarte_motiv01.jpg' %}" alt="First" width="1200" height="600" title="by Sandra Lehecka"/>
                <div class="carousel-caption"></div>
            </div>
            <div class="item">
                <img src="{% static 'webpage/img/ACDH_Panorama_Postkarte_motiv02.jpg' %}" alt="a nice feature picture" width="1200" height="600" title="by Sandra Lehecka"/>
                <div class="carousel-caption"></div>
            </div>
        </div><!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><!--<span class="sr-only">Previous</span>--></a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><!--<span class="sr-only">Next</span>--></a>
    </div>
    <h1 style="text-align:center">{% projects_metadata 'title' %}</h1>
    <h3>{% projects_metadata 'subtitle' %}</h3>
    <p>{% projects_metadata 'description' %}</p>
</div>

{% endblock %}

webpage/templates/webpage/user_login.html
{% extends "webpage/base.html" %}

{% block content %}

<div class="container"></br>
{% if form.errors %}

<p style="color: red;">Please correct the error{{ form.errors|pluralize }} below.</p>

{% endif %}

{% load crispy_forms_tags %}

{% crispy form form.helper %}

</div>
{% endblock %}

webpage/templates/webpage/user_logout.html
{% extends "webpage/base.html" %}

{% block Titel %}logout{% endblock %}

{% block content %}

<div class="jumbotron container">
    
    <h1>Sayōnara!</h1>
    
    <p>You've signed out</p>

</div>

{% endblock content %}